# Generated by Django 6.0.2 on 2026-05-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expense_options_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='current_live_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
