# Generated by Django 6.0.2 on 2026-05-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_wishlistitem_current_live_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='is_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
